{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      name: {{ .Values.db.name }}
      labels:
        app: {{ .Values.db.name }}
        {{- if .Values.db.watchNamespace }}
        appNamespace: {{ .Values.db.watchNamespace }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.db.name }}
        image: {{ .Values.db.image }}
        command:
        - {{ .Values.db.runCommand }}
        - "/db-config/redis.conf"
        ports:
        - containerPort: {{ .Values.db.port }}
          name: {{ .Values.db.name }}
        volumeMounts:
        - mountPath: /db-config
          name: config
      volumes:
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf
{{- end -}}
