{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matgip.secretName" . }}
  namespace: {{ .Values.web.watchNamespace }}
type: Opaque
data:
  map-url: {{ .Values.web.map.url }}
  map-client-id: {{ .Values.web.map.clientId }}
  news-client-id: {{ .Values.web.news.clientId }}
  news-client-secret: {{ .Values.web.news.clientSecret }}
  token-secret: {{ .Values.web.authorization.token }}
{{- end -}}