{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  labels:
    app: {{ .Values.web.name }}
spec:
  selector:
    app: {{ .Values.web.name }}
    {{- if .Values.web.watchNamespace }}
    appNamespace: {{ .Values.web.watchNamespace }}
    {{- end }}
  type: NodePort
  ports:
  - protocol: TCP
    name: matgip-web
    nodePort: 31637
    port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
{{- end -}}