{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  template:
    metadata:
      name: {{ .Values.web.name }}
      labels:
        app: {{ .Values.web.name }}
        {{- if .Values.web.watchNamespace }}
        appNamespace: {{ .Values.web.watchNamespace }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "matgip.serviceAccountName" . }}
      containers:
      - name: {{ .Values.web.name }}
        image: {{ .Values.web.image }}
        ports:
        - containerPort: {{ .Values.web.port }}
          name: {{ .Values.web.name }}
        env:
        - name: REDIS_HOST
          value: {{ .Values.web.dbName }}
        - name: NAVER_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "matgip.secretName" . }}
              key: news-client-id
        - name: NAVER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "matgip.secretName" . }}
              key: news-client-secret
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "matgip.secretName" . }}
              key: token-secret
{{- end -}}