{{- if .Values.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "matgip.clusterRoleName" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
  - post
  - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "matgip.clusterRoleName" . }}
  namespace: {{ .Values.web.watchNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "matgip.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "matgip.serviceAccountName" . }}
  namespace: {{ .Values.web.watchNamespace }}
{{- end -}}
